### ISSUE TITLE
Sort object keys before serializing?

### ISSUE THREAD

**Issue by christoomey** [CareMessagePlatform/rspec-request_snapshot#24]
Hello and thanks for the wonderful project!

I'm currently doing some performance work on an API which has changed the order in which object keys are sorted, but otherwise not changed the output. Unfortunately, this is causing my snapshot tests to fail, despite the responses being functionally the same.

I've resorted to using [`jq -S`](https://stedolan.github.io/jq/) to recursively sort the keys in my snapshots to validate that the before and after are identical other than key order.

My sense is that for most cases, ignoring key order (likely by sorting before serializing) would be useful to avoid false negatives, but I could also see some edge cases where key order would matter, so might make sense to expose as a configuration option rather than default behavior.

**Comment by bruno-campos** [comment]
Hi Chris,

Thank you! For your issue, we don't actually consider key ordering when matching snapshots. We have been using snapshots without account for key ordering. Can you provide some examples when that happens?

With the example, it will be simpler to see what is going on and fix it.

**Comment by christoomey** [comment]
Hi @bruno-campos, thanks for the quick reply. Looking a bit closer at the spec I was working with, I now see that it was other unrelated differences that were causing it to fail. Glad to hear this gem already ignores the key order! Thanks again for the great work here. (Closing this now as I don't believe there is actually any issues, but thanks again).
